config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  mount Sidekiq::Web => '/sidekiq'

  resources :scraper_expressions, only: [:index, :new, :destroy, :create]

  namespace :api do
    namespace :v1 do
      resources :products, except: [:edit, :update] do
        member do
          get :fetch
        end
      end
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/enumerables.rb
concern :Enumerables do
  class_methods do
    def setup_enumerable(array, name)
      setup_queries(array, name)
      setup_setters(array, name)
      setup_scopes(array, name)
    end

    def setup_queries(array, name)
      array.each do |item|
        define_method "#{item}?" do
          self.send(name) == item
        end
      end
    end

    def setup_setters(array, name)
      array.each do |item|
        define_method "#{item}!" do
          self.update!(name => item)
        end
      end
    end

    def setup_scopes(array, name)
      array.each do |item|
        class_eval do
          scope item, -> { where(name => item) }
        end
      end
    end
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  include Enumerables

  # ======= Constants
  STATUSES = {
    inactive: 'inactive',
    active: 'active'
  }

  # ======= Scopes
  setup_enumerable(STATUSES.values, :status)

  # ======= Validations
  validates :asin, presence: true, uniqueness: true
end

app/models/scraper_expression.rb
class ScraperExpression < ActiveRecord::Base
  # Important that we dont allow breaking of clauses. That is:
  # "input".gsub('u', '');AnotherClause
  # the above is not allowed
  validates :expression, format: { without: /(\);|[a-zA-Z0-9];)/ }
end

app/controllers/api/v1/products_controller.rb
class Api::V1::ProductsController < ApiController
  before_action :validate_asin_query, only: [:fetch]
  before_action :require_resource, only: [:destroy, :show]

  def index
    render json: Product.active.order("created_at desc")
  end

  def show
    render json: product
  end

  def destroy
    if product.destroy
      render json: { success: true }
    end
  end

  def fetch
    render json: ProductCreationService.new(params[:id]).fetch_or_create(force: true)
  end

  private

  def product
    @product ||= Product.where(asin: params[:id]).first
  end

  def require_resource
    unless product.present?
      render json: {}, status: :not_found
      return
    end
  end

  def validate_asin_query
    unless params[:id].match(AmazonProduct::ASIN_VALID_QUERY_REGEX)
      render json: { error: "Invalid ASIN number" }, status: :bad_request
      return
    end
  end
end

app/controllers/api_controller.rb
class ApiController < ActionController::API
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/product_controller.rb
class ProductController < ApplicationController
  def index
  end
end

app/controllers/scraper_expressions_controller.rb
class ScraperExpressionsController < ApplicationController
  before_action :load_expression, only: [:destroy]

  def index
    @scraper_expressions = ScraperExpression.all
  end

  def new
    @scraper_expression = ScraperExpression.new
  end

  def create
    scraper_expression = ScraperExpression.create(scraper_expression_params)
    redirect_to scraper_expressions_path
  end

  def destroy
    @scraper_expression.destroy
    redirect_to scraper_expressions_path
  end

  private

  def scraper_expression_params
    params.require(:scraper_expression).permit(:key, :expression)
  end

  def load_expression
    @scraper_expression = ScraperExpression.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AsinScraper</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>

  <body>
    <div class='container'>
      <%= yield %>
    </div>

    <script src="//cdnjs.cloudflare.com/ajax/libs/angular.js/1.7.8/angular.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/angular.js/1.7.8/angular-route.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/angular.js/1.7.8/angular-resource.min.js"></script>
  </body>
</html>

app/views/product/index.html.haml
%div(ng-app="asin_scraper")
  %div(navbar='true')

app/views/scraper_expressions/index.html.erb
<div class='card shadow'>
  <%= link_to "Add a New scraper_expression", new_scraper_expression_path, class: 'btn btn-primary' %>
  <hr>
  <table class='table'>
    <% @scraper_expressions.each do |scraper_expression| %>
      <tr>
        <td><%= link_to scraper_expression.key, scraper_expression_path(scraper_expression) %></td>
        <td><%=  scraper_expression.expression %></td>
        <td><%= button_to 'Remove', scraper_expression_path(scraper_expression),
                method: 'delete',
                class: 'btn btn-warning',
                data: { confirm: 'Are you sure?' } %></td>
    <% end %>
  </table>
</div>

app/views/scraper_expressions/new.html.erb
<div>
  <div class='row'>
    <div class='col-md-4 shadow'>
      <h3>Create a Scraper Expression</h3>
      <%= form_with model: @scraper_expression do |form| %>

        <label>Choose what the expression is for:</label>
        <br>
        <div class='form-group'>
          <%= form.label :key, 'image_url', :value => 'image_url' %>
          <%= form.radio_button :key, "image_url" %>
        </div>

        <div class='form-group'>
          <%= form.label :key, 'title', :value => 'title' %>
          <%= form.radio_button :key, "title" %>
        </div>

        <div class='form-group'>
          <%= form.label :key, 'dimensions', :value => 'dimensions' %>
          <%= form.radio_button :key, "dimensions" %>
        </div>

        <div class='form-group'>
          <%= form.label :key, 'best_seller_rank', :value => 'best_seller_rank' %>
          <%= form.radio_button :key, "best_seller_rank" %>
        </div>

        <div class='form-group'>
          <%= form.label :key, 'category', :value => 'category' %>
          <%= form.radio_button :key, "category" %>
        </div>


        <%= form.text_field :expression,
            placeholder: "Expression to be evaluated within the dom",
            class: 'form-control' %>

        <hr>
        <div>
          <%= form.submit "Create", class: 'btn btn-danger' %>
        </div>
        <hr>
      <% end %>
    </div>
  </div>
</div>